=== larionovda/TaskXML/xml/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="products" type="productsType"/>
    <xs:complexType name="subjectType">
        <xs:sequence>
            <xs:element name="producer" type="xs:string"/>
            <xs:element name="model">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[a-zA-Z]{2}[0-9]{3}"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="start" type="xs:string"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="quantity" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="subCategoryType">
        <xs:sequence>
            <xs:element type="subjectType" name="subject" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:element type="subCategoryType" name="subCategory"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="sign" use="optional"/>
    </xs:complexType>
    <xs:complexType name="productsType">
        <xs:sequence>
            <xs:element type="categoryType" name="category" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== larionovda/TaskXML/xml/products.xml
<?xml version="1.0" encoding="UTF-8"?>


<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
  <category sign="shirt">

    <subCategory>
      <subject>
        <producer>China</producer>
        <model>sd234</model>
        <start>10-01-2018</start>
        <color>red</color>
        <price>2000.50</price>
        <quantity>10</quantity>
      </subject>
      <subject>
        <producer>Russia</producer>
        <model>sd555</model>
        <start>12.11.2015</start>
        <color>white</color>
        <price>1000.30</price>
        <quantity>15</quantity>
      </subject>
    </subCategory>
  </category>

  <category sign="skirt">
    <subCategory>
      <subject>
        <producer>Korea</producer>
        <model>sd999</model>
        <start>17-09-2017</start>
        <color>yellow</color>
        <price>1500.10</price>
        <quantity>20</quantity>
      </subject>
      <subject>
        <producer>China</producer>
        <model>sd222</model>
        <start>25-08-2018</start>
        <color>black</color>
        <price>1300.00</price>
        <quantity>14</quantity>
      </subject>
    </subCategory>
  </category>

</products>
